"""Resend an Irvine All-Stars parent invite when the old link expired.

Looks up the parent by email in tryout_registrations (selected/alternate),
creates a fresh invite row (token + 7-day expiry auto-generated by DB),
emails them a branded link via Resend, and prints the copy-paste URL.

Skips parents who already have a profile (already signed up).
Reuses an existing unused + unexpired invite token if one exists.

Usage:
  python3 scripts/resend_expired_invite.py --email foo@bar.com
  python3 scripts/resend_expired_invite.py --email foo@bar.com --dry-run
  python3 scripts/resend_expired_invite.py --all-expired                 # resend to every selected/alt parent without a profile whose invites all expired
  python3 scripts/resend_expired_invite.py --all-expired --dry-run
"""

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from urllib.error import HTTPError
from urllib.parse import quote
from urllib.request import Request, urlopen


HERE = Path(__file__).resolve().parent


def load_env(path: Path) -> dict[str, str]:
    env: dict[str, str] = {}
    if not path.exists():
        return env
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        env[k.strip()] = v.strip().strip('"').strip("'")
    return env


ENV = {**os.environ, **load_env(HERE.parent / ".env.local")}
SUPA = ENV["NEXT_PUBLIC_SUPABASE_URL"].rstrip("/")
KEY = ENV["SUPABASE_SERVICE_ROLE_KEY"]
RESEND = ENV["RESEND_API_KEY"]
SITE = "https://irvineallstars.com"


def supa(method: str, path: str, body: dict | list | None = None) -> list[dict]:
    req = Request(
        f"{SUPA}/rest/v1/{path}",
        data=json.dumps(body).encode() if body is not None else None,
        headers={
            "apikey": KEY,
            "Authorization": f"Bearer {KEY}",
            "Accept-Profile": "irvine_allstars",
            "Content-Profile": "irvine_allstars",
            "Content-Type": "application/json",
            "Prefer": "return=representation",
        },
        method=method,
    )
    try:
        with urlopen(req, timeout=30) as r:
            txt = r.read().decode() or "[]"
            return json.loads(txt) if txt.startswith(("[", "{")) else []
    except HTTPError as e:
        raise RuntimeError(f"{method} {path} -> HTTP {e.code}: {e.read().decode()}")


def parent_lookup(email: str) -> list[dict]:
    e = quote(email)
    return supa(
        "GET",
        f"tryout_registrations?status=in.(selected,alternate)"
        f"&or=(parent_email.ilike.{e},secondary_parent_email.ilike.{e})"
        f"&select=id,parent_name,parent_email,secondary_parent_email,player_first_name,player_last_name,division,team_id,current_team",
    )


def has_profile(email: str) -> bool:
    e = quote(email)
    rows = supa("GET", f"profiles?email=ilike.{e}&select=id")
    return bool(rows)


def existing_valid_invite(email: str) -> dict | None:
    e = quote(email)
    rows = supa(
        "GET",
        f"invites?email=ilike.{e}&used=eq.false"
        f"&expires_at=gt.{quote(datetime.now(timezone.utc).isoformat())}"
        f"&select=id,token,expires_at&order=created_at.desc",
    )
    return rows[0] if rows else None


def create_invite(parent_email: str, reg: dict) -> dict:
    body = {
        "email": parent_email,
        "role": "parent",
    }
    if reg.get("division"):
        body["division"] = reg["division"]
    if reg.get("parent_name") and reg["parent_email"].lower() == parent_email.lower():
        body["parent_name"] = reg["parent_name"]
    if reg.get("player_first_name"):
        body["child_first_name"] = reg["player_first_name"]
    if reg.get("player_last_name"):
        body["child_last_name"] = reg["player_last_name"]
    if reg.get("current_team"):
        body["current_team"] = reg["current_team"]
    res = supa("POST", "invites", body)
    return res[0]


def build_html(url: str, parent_name: str | None, kids: list[str], team_label: str | None) -> str:
    greet = f"Hi {parent_name}," if parent_name else "Hi,"
    if len(kids) == 1:
        kid_phrase = f"<strong>{kids[0]}</strong>"
    elif len(kids) > 1:
        kid_phrase = "<strong>" + " and ".join(kids) + "</strong>"
    else:
        kid_phrase = "your player"
    team_phrase = f" ({team_label})" if team_label else ""
    return f"""<!DOCTYPE html>
<html><body style="margin:0;padding:0;background-color:#FAFAF8;font-family:system-ui,-apple-system,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background-color:#FAFAF8;padding:40px 20px;">
<tr><td align="center">
<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;">
<tr><td style="background-color:#0A2342;padding:30px 40px;text-align:center;">
<h1 style="color:#FFFFFF;font-size:24px;font-weight:700;margin:0;letter-spacing:2px;text-transform:uppercase;">Irvine All-Stars</h1>
</td></tr>
<tr><td style="background-color:#C1121F;height:4px;font-size:0;line-height:0;">&nbsp;</td></tr>
<tr><td style="background-color:#FFFFFF;padding:40px;">
<h2 style="color:#0A2342;font-size:20px;font-weight:700;margin:0 0 16px 0;text-transform:uppercase;letter-spacing:1px;">Your Invite Link Has Been Refreshed</h2>
<p style="color:#4B5563;font-size:16px;line-height:1.6;margin:0 0 16px 0;">{greet}</p>
<p style="color:#4B5563;font-size:16px;line-height:1.6;margin:0 0 24px 0;">Your previous invite link expired. Here's a fresh one so you can finish setting up your Irvine All-Stars parent account for {kid_phrase}{team_phrase}.</p>
<table cellpadding="0" cellspacing="0" style="margin:0 0 24px 0;" width="100%">
<tr><td align="center">
<a href="{url}" style="display:inline-block;background-color:#C1121F;color:#FFFFFF;font-size:16px;font-weight:700;text-decoration:none;padding:14px 32px;border-radius:6px;text-transform:uppercase;letter-spacing:1px;">Set Up Your Account</a>
</td></tr></table>
<p style="color:#9CA3AF;font-size:13px;line-height:1.5;margin:0 0 24px 0;text-align:center;">This link expires in 7 days and can only be used once.</p>
<p style="color:#4B5563;font-size:14px;line-height:1.6;margin:0 0 24px 0;">Once you're in, please upload your player's birth certificate so we can finalize the team binder.</p>
<p style="color:#4B5563;font-size:16px;line-height:1.6;margin:0;">Thanks,<br><strong style="color:#0A2342;">Irvine All-Stars</strong><br><a href="mailto:AllStars@irvinepony.com" style="color:#0A2342;text-decoration:underline;">AllStars@irvinepony.com</a></p>
</td></tr>
<tr><td style="background-color:#0A2342;padding:20px 40px;text-align:center;">
<p style="color:rgba(255,255,255,0.5);font-size:12px;margin:0;line-height:1.5;">Irvine Pony Baseball &bull; 2026 All-Stars Season<br><a href="https://irvineallstars.com" style="color:rgba(255,255,255,0.7);text-decoration:underline;">irvineallstars.com</a></p>
</td></tr>
</table></td></tr></table></body></html>"""


def send_email(to_email: str, html: str) -> dict:
    payload = {
        "from": "Irvine All-Stars <AllStars@irvineallstars.com>",
        "reply_to": "AllStars@irvinepony.com",
        "to": [to_email],
        "subject": "Your Irvine All-Stars invite link (refreshed)",
        "html": html,
    }
    req = Request(
        "https://api.resend.com/emails",
        data=json.dumps(payload).encode(),
        headers={
            "Authorization": f"Bearer {RESEND}",
            "Content-Type": "application/json",
            "User-Agent": "curl/8.7.1",
        },
        method="POST",
    )
    try:
        with urlopen(req, timeout=30) as r:
            return json.loads(r.read().decode())
    except HTTPError as e:
        raise RuntimeError(f"Resend HTTP {e.code}: {e.read().decode()}")


def team_name_by_id(team_id: str | None, cache: dict) -> str | None:
    if not team_id:
        return None
    if team_id in cache:
        return cache[team_id]
    rows = supa("GET", f"teams?id=eq.{team_id}&select=team_name")
    name = rows[0]["team_name"] if rows else None
    cache[team_id] = name
    return name


def resend_one(email: str, *, dry_run: bool, team_cache: dict, preview_to: str | None = None) -> tuple[bool, str]:
    """Returns (sent, reason). If preview_to set, email goes there instead of `email`
    (token still tied to `email`, so the real parent can still use it later)."""
    email = email.strip().lower()
    if has_profile(email):
        return False, "already has profile (signed up)"
    regs = parent_lookup(email)
    if not regs:
        return False, "no selected/alternate registration for this email"

    # primary email match wins; otherwise use first reg for naming context
    primary_regs = [r for r in regs if (r.get("parent_email") or "").lower() == email]
    ctx_reg = primary_regs[0] if primary_regs else regs[0]
    kids = [f"{r['player_first_name']} {r['player_last_name']}" for r in regs]
    team_label = team_name_by_id(ctx_reg.get("team_id"), team_cache)
    parent_name = ctx_reg.get("parent_name") if primary_regs else None

    existing = existing_valid_invite(email)
    if dry_run:
        if existing:
            url = f"{SITE}/auth/invite/{existing['token']}"
            print(f"[DRY] {email}: REUSE existing valid token; kids={kids}; team={team_label}")
            print(f"      URL: {url}")
        else:
            print(f"[DRY] {email}: would create NEW invite; kids={kids}; team={team_label}")
        return False, "dry-run"

    if existing:
        token = existing["token"]
        reused = True
    else:
        invite = create_invite(email, ctx_reg)
        token = invite["token"]
        reused = False

    url = f"{SITE}/auth/invite/{token}"
    label = f"{'REUSED' if reused else 'NEW'} token; kids={kids}; team={team_label}"
    html = build_html(url, parent_name, kids, team_label)
    recipient = preview_to or email
    res = send_email(recipient, html)
    tag = f"[PREVIEW->{recipient}] " if preview_to else ""
    print(f"{tag}SENT  {email}: resend_id={res.get('id')} {label}")
    print(f"      URL: {url}")
    return True, "sent"


def find_all_expired_emails() -> list[str]:
    """Return distinct parent emails (primary + secondary) for selected/alt
    registrations whose owner has no profile and whose newest invite is
    used=false + expired (or has no invites)."""
    regs = supa(
        "GET",
        "tryout_registrations?status=in.(selected,alternate)"
        "&select=parent_email,secondary_parent_email",
    )
    emails: set[str] = set()
    for r in regs:
        for k in ("parent_email", "secondary_parent_email"):
            v = (r.get(k) or "").strip().lower()
            if v:
                emails.add(v)

    now = datetime.now(timezone.utc).isoformat()
    needs = []
    for e in sorted(emails):
        if has_profile(e):
            continue
        # check newest invite
        rows = supa(
            "GET",
            f"invites?email=ilike.{quote(e)}&select=expires_at,used&order=created_at.desc&limit=1",
        )
        if not rows:
            needs.append(e)
            continue
        latest = rows[0]
        if latest["used"]:
            continue
        if latest["expires_at"] < now:
            needs.append(e)
    return needs


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--email", help="single parent email to resend to")
    ap.add_argument("--all-expired", action="store_true", help="resend to every parent without a profile whose latest invite expired")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--preview-to", help="route emails to this address instead of the real parents (for proofing copy/render)")
    args = ap.parse_args()

    if not args.email and not args.all_expired:
        ap.error("pass --email EMAIL or --all-expired")

    team_cache: dict = {}
    if args.email:
        sent, reason = resend_one(args.email, dry_run=args.dry_run, team_cache=team_cache, preview_to=args.preview_to)
        if not sent and reason != "dry-run":
            print(f"SKIP {args.email}: {reason}")
        return

    targets = find_all_expired_emails()
    print(f"Found {len(targets)} parent(s) needing a fresh invite.\n")

    # In preview mode, only process the first target (one sample email)
    if args.preview_to:
        targets = targets[:1]
        print(f"--preview-to set; sending 1 sample to {args.preview_to}\n")

    sent_count = 0
    skip_count = 0
    for e in targets:
        try:
            sent, reason = resend_one(e, dry_run=args.dry_run, team_cache=team_cache, preview_to=args.preview_to)
            if sent:
                sent_count += 1
            elif reason != "dry-run":
                print(f"SKIP {e}: {reason}")
                skip_count += 1
        except Exception as ex:
            print(f"ERROR {e}: {ex}")
            skip_count += 1
    print(f"\nDone. sent={sent_count} skipped/errored={skip_count} total={len(targets)}")


if __name__ == "__main__":
    main()
